spring:
  application:
    name: chapter6-memory-advanced

  # Spring AI OpenAI 設定
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 1000

  # 資料庫設定 (開發環境使用 H2)
  datasource:
    url: jdbc:h2:mem:advanceddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  # JDBC 設定
  sql:
    init:
      mode: always

# 伺服器設定
server:
  port: 8086

# 日誌設定
logging:
  level:
    com.example.memory.advanced: DEBUG
    org.springframework.ai: DEBUG

# 進階記憶管理設定
app:
  memory:
    # 智能摘要設定
    smart-summary:
      enabled: true
      threshold: 50              # 觸發摘要的訊息數閾值
      keep-recent: 20            # 保留最近的訊息數
      summarize-count: 30        # 每次摘要的訊息數

    # 混合記憶策略設定
    hybrid:
      enabled: true
      short-term-weight: 0.6     # 短期記憶權重
      long-term-weight: 0.4      # 長期記憶權重
      max-short-term: 20         # 最大短期記憶數
      max-long-term: 10          # 最大長期記憶數

    # 記憶優化設定
    optimization:
      enabled: true
      max-messages: 100          # 單一對話最大訊息數
      auto-cleanup: true         # 啟用自動清理
      retention-days: 30         # 記憶保留天數
      cleanup-interval: 3600000  # 清理間隔 (毫秒)
