version: '3.8'

services:
  # PgVector 數據庫
  pgvector:
    image: ankane/pgvector:latest
    container_name: advanced-rag-pgvector
    environment:
      POSTGRES_DB: advanced_rag
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass123
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d advanced_rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network

  # Redis 快取和會話管理
  redis:
    image: redis:7-alpine
    container_name: advanced-rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - rag-network

  # Prometheus 監控
  prometheus:
    image: prom/prometheus:latest
    container_name: advanced-rag-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - rag-network

  # Grafana 可視化
  grafana:
    image: grafana/grafana:latest
    container_name: advanced-rag-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - rag-network

volumes:
  pgvector_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  rag-network:
    driver: bridge
