spring:
  application:
    name: spring-ai-advanced
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini  # 支援多模態和 Tool Calling
          temperature: 0.7
          max-tokens: 2000
          stream: true

    # Groq 配置（可選）
    groq:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-70b-versatile

# 應用程式配置
server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 50MB
      file-size-threshold: 2KB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 提示詞範本配置
app:
  prompt:
    templates:
      library:
        explain: |
          作為一個 {role} 專家，請詳細說明 {topic}。

          請包含：
          1. 核心概念
          2. 主要特性
          3. 使用場景
          4. 實際範例

          目標受眾：{audience}
          回答語言：{language}

        code-review: |
          你是一個資深的 {language} 程式碼審查專家。

          請審查以下程式碼：
          ```{language}
          {code}
          ```

          請提供：
          1. 程式碼品質評估
          2. 潛在問題識別
          3. 改進建議
          4. 最佳實踐建議

          請用繁體中文回答。

      defaults:
        language: 繁體中文
        role: 技術專家
        audience: 中級開發者

# 檔案上傳配置
file:
  upload:
    path: ./uploads
    max-size: 25MB
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - audio/mpeg
      - audio/wav
      - audio/mp4
      - video/mp4
      - video/avi

# 日誌配置
logging:
  level:
    org.springframework.ai: DEBUG
    com.example: DEBUG
    org.springframework.web.multipart: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 應用程式資訊
management:
  info:
    env:
      enabled: true

info:
  app:
    name: Spring AI Advanced Features
    description: Spring AI 進階功能展示 - 提示詞範本、多模態、Tool Calling
    version: 1.0.0
